model:
  model_name: "ollama_chat/gpt-oss:120b"
  model_class: "litellm_textbased"
  litellm_model_registry: "/home/22pf2/BenchmarkLLMAgent/configs/p2p_pipeline/ollama_gpt_oss_registry.json"
  cost_tracking: "ignore_errors"
  model_kwargs:
    temperature: 0.0
    api_base: "http://localhost:11435"
