#!/usr/bin/env python3
"""
Rescore every stored condition in the paper under the executed FAIL_TO_PASS criterion.

Extends strict_matrix_279.py past the Qwen3 matrix to the zero-shot enhancer, the
reward-gated selective enhancer, and the GPT-5-mini cross-model check -- every claim whose
scoring pass left per-test status.json behind. Costs no containers.

Strictly resolved = every executed F2P test passes and every executed P2P test passes,
using the executed labels in data/stage6_all279_f2p_derived.json.

Only 85 of 279 instances carry an executed fail->pass test, so every row prints its own n.
The first tranche's per-test artifacts were lost and have been regenerated by
rescore_tranche100.py over its 28 gradeable instances. Rows
are paired: an instance counts only when both arms of that comparison have an artifact or
a recorded empty submission, so baseline and enhanced are always the same instance set.
"""
import json, collections
from pathlib import Path
from scipy.stats import binomtest

ROOT = Path("/home/22pf2/BenchmarkLLMAgent")
LAB  = json.load(open(ROOT/"data/stage6_all279_f2p_derived.json"))
GRAD = [i for i, v in LAB.items() if v["FAIL_TO_PASS"]]

QWEN = [ROOT/"runs/stage6_100_rescore",          # first tranche, artifacts regenerated
        ROOT/"runs/stage6_new100_scores/matrix200_extra100_20260630_174724",
        ROOT/"runs/stage6_new100_scores_sa/matrix200_extra100_20260630_174724",
        ROOT/"runs/stage6_new182_scores/matrix382_extra182_20260706_134335"]
ZERO = [ROOT/"runs/stage6_zeroshot_scores"]
CL   = [ROOT/"runs/cl_enhanced_scores/cl_enhanced_382_20260730_173424"]
OAI  = [ROOT/"runs/stage6_openai_scores"]

def st(roots, arm, iid):
    for r in roots:
        for h in (r/arm).glob(f"*/{iid}/status.json"):
            try: return json.load(open(h))
            except Exception: pass
    return None

def strict(roots, arm, iid):
    s = st(roots, arm, iid)
    if s is None: return None
    lab = LAB[iid]
    return (all(s.get(t) == "pass" for t in lab["FAIL_TO_PASS"])
            and all(s.get(t, "pass") == "pass" for t in lab["PASS_TO_PASS"]))

COMPARISONS = []
for s in ["openhands", "aider", "swe_agent"]:
    for e in ["aider", "openhands", "swe_agent"]:
        COMPARISONS.append((f"Qwen3  enh:{e} -> sol:{s}", QWEN, f"baseline__solver_{s}",
                            QWEN, f"enh_{e}__solver_{s}"))
    COMPARISONS.append((f"Qwen3  zero-shot -> sol:{s}", QWEN, f"baseline__solver_{s}",
                        ZERO, f"enh_simple__solver_{s}"))
    COMPARISONS.append((f"Qwen3  CL(gated) -> sol:{s}", QWEN, f"baseline__solver_{s}",
                        CL, f"enh_cl_enhanced__solver_{s}"))
COMPARISONS.append(("GPT-5-mini  enh:aider -> sol:openhands", OAI, "baseline", OAI, "enh_aider"))

print(f"executed-F2P gradeable instances: {len(GRAD)} of 279\n")
print(f"{'comparison':40s} {'n':>4} {'base':>5} {'enh':>4} {'Δ':>4} {'resc':>5} {'brk':>4} {'p':>7}")
print("-"*80)
rows = []
for label, br, ba, er, ea in COMPARISONS:
    ids = [i for i in GRAD if st(br, ba, i) is not None or st(er, ea, i) is not None]
    if not ids:
        print(f"{label:40s} {'--':>4}   (no artifacts)")
        continue
    b = e_ = r = k = 0
    for i in ids:
        bb = bool(strict(br, ba, i)); ee = bool(strict(er, ea, i))
        b += bb; e_ += ee; r += (not bb and ee); k += (bb and not ee)
    p = binomtest(r, r+k, 0.5).pvalue if r+k else 1.0
    print(f"{label:40s} {len(ids):4d} {b:5d} {e_:4d} {e_-b:+4d} {r:5d} {k:4d} {p:7.3f}")
    rows.append({"comparison": label, "n": len(ids), "baseline": b, "enh": e_,
                 "delta": e_-b, "rescues": r, "breakages": k, "mcnemar_p": p})

print("-"*80)
tr = sum(x["rescues"] for x in rows); tk = sum(x["breakages"] for x in rows)
tb = sum(x["baseline"] for x in rows); te = sum(x["enh"] for x in rows)
print(f"{'POOLED (all comparisons)':40s} {sum(x['n'] for x in rows):4d} {tb:5d} {te:4d} "
      f"{te-tb:+4d} {tr:5d} {tk:4d} {binomtest(tr,tr+tk,0.5).pvalue if tr+tk else 1.0:7.3f}")
sig = [x for x in rows if x["mcnemar_p"] < 0.05]
print(f"\ncomparisons with McNemar p<0.05: {len(sig)}/{len(rows)}  {[x['comparison'] for x in sig]}")
json.dump(rows, open(ROOT/"data/stage6_strict_all_conditions.json", "w"), indent=1)
print(f"Wrote data/stage6_strict_all_conditions.json")
